[package]
name = "pop-launcher"
version = "1.2.1"
license = "MPL-2.0"
authors = ["Michael Aaron Murphy <mmstick@pm.me>"]
description = "Library for writing plugins and frontends for pop-launcher"
repository = "https://github.com/pop-os/launcher"
edition = "2018"

[workspace]
members = ["bin", "plugins", "service", "toolkit"]

[dependencies]
const_format = "0.2.22"
dirs = "4.0.0"
futures = "0.3.21"
serde = { version = "1.0.136", features = ["derive"] }
serde_json = "1.0.79"
serde_with = "1.12.0"

[profile.release]
lto = true
panic = "abort"
strip = true

[dependencies.tokio]
version = "1.17.0"
features = ["io-std", "io-util"]

[dependencies.tokio-stream]
version = "0.1.8"
features = ["io-util"]

[patch.crates-io]
wayland-protocols = { git = "https://github.com/smithay/wayland-rs", version = "0.30.0-beta.9"}
wayland-sys = { git = "https://github.com/smithay/wayland-rs", version = "0.30.0-beta.9"}
wayland-backend = { git = "https://github.com/smithay/wayland-rs", version = "0.1.0-beta.9"}
wayland-scanner = { git = "https://github.com/smithay/wayland-rs", version = "0.30.0-beta.9"}
wayland-client = { git = "https://github.com/smithay/wayland-rs", version = "0.30.0-beta.9"}
